export { SceneManager } from './SceneManager'
export type { SceneManagerOptions, ControlMode } from './SceneManager'
export { logger, createLogger, Logger } from './Logger'
export type { LogLevel } from './Logger'

// Gameplay Framework (位于 engine/gameplay 下)
export { Actor } from './gameplay/Actor'
export { Component } from './gameplay/Component'
export { SpawnComponent } from './gameplay/SpawnComponent'
export { Pawn } from './gameplay/Pawn'
export { PlayerController } from './gameplay/PlayerController'
export { GameMode } from './gameplay/GameMode'
export { GameState } from './gameplay/GameState'
export { GameInstance, NullGameInstance } from './gameplay/GameInstance'
export type { GameInstanceCallbacks } from './gameplay/GameInstance'
export { Game } from './gameplay/Game'
export { World } from './gameplay/World'
export { CameraComponent } from './gameplay/CameraComponent'
export { PlayerCameraManager } from './gameplay/PlayerCameraManager'
export { InputComponent } from './gameplay/InputComponent'
export type { InputEventType } from './gameplay/InputComponent'
export type { WorldBuilder, WorldBuildConfig, WorldAsset } from './gameplay/WorldAsset'
export { WorldRegistry } from './gameplay/WorldRegistry'
export { GameFactoryRegistry } from './gameplay/GameFactoryRegistry'
export type { GameInstanceFactory } from './gameplay/GameFactoryRegistry'
export { GameUI } from './gameplay/GameUI'
export type { GameUIElement, GameUIOverlay, CreateTextOptions, CreateOverlayOptions } from './gameplay/GameUI'
export { Gizmos, gizmos } from './gameplay/Gizmos'
export type { GizmoColor } from './gameplay/Gizmos'
