export { PreviewSceneManager } from './scene/PreviewSceneManager'
export { GameSceneManager } from './scene/GameSceneManager'
export type { PreviewSceneManagerOptions, ControlMode } from './scene/PreviewSceneManager'
export { logger, Logger } from './Logger'
export type { LogLevel } from './Logger'

// Gameplay Framework (位于 engine/gameplay 下)
export { Actor } from './gameplay/entity/Actor'
export { Component } from './gameplay/entity/Component'
export { SpawnComponent } from './gameplay/entity/SpawnComponent'
export { Pawn } from './gameplay/entity/Pawn'
export { PlayerController } from './gameplay/input/PlayerController'
export { GameMode } from './gameplay/gameflow/GameMode'
export { GameState } from './gameplay/gameflow/GameState'
export { GameInstance, NullGameInstance } from './gameplay/gameflow/GameInstance'
export type { GameInstanceCallbacks } from './gameplay/gameflow/GameInstance'
export { Game } from './gameplay/gameflow/Game'
export { World } from './gameplay/gameflow/World'
export { CameraComponent } from './gameplay/input/CameraComponent'
export type { CameraMode } from './gameplay/input/CameraComponent'
export { SpriteComponent } from './gameplay/rendering/SpriteComponent'
export { ClickableComponent } from './gameplay/physics/ClickableComponent'
export { loadTexture, clearTextureCache } from './gameplay/scene/TextureLoader'
export { PlayerCameraManager } from './gameplay/input/PlayerCameraManager'
export { InputComponent } from './gameplay/input/InputComponent'
export type { InputEventType } from './gameplay/input/InputComponent'
export type { SkyboxConfig } from './gameplay/scene/SceneAsset'
export { loadScene } from './gameplay/scene/SceneLoader'
export type { SceneGroup } from './gameplay/scene/SceneLoader'
export type { SceneAsset, SceneNode, SpriteNode, MaterialProps } from './gameplay/scene/SceneAsset'
export { GameFactoryRegistry } from './gameplay/tools/GameFactoryRegistry'
export type { GameInstanceFactory } from './gameplay/tools/GameFactoryRegistry'
export { GameModeRegistry } from './gameplay/tools/GameModeRegistry'
export { AssetRegistry } from './gameplay/tools/AssetRegistry'
export { ComponentRegistry } from './gameplay/tools/ComponentRegistry'
export type { ComponentFactory, ComponentConfigurator } from './gameplay/tools/ComponentRegistry'
export { ActorRegistry } from './gameplay/tools/ActorRegistry'
export type { ActorFactory } from './gameplay/tools/ActorRegistry'
export { BlueprintRegistry } from './gameplay/blueprint/BlueprintRegistry'
export type {
  BlueprintAsset,
  BlueprintComponentDef,
  BlueprintChildDef,
  ResolvedBlueprint,
} from './gameplay/blueprint/BlueprintAsset'
export { registerBuiltinComponents } from './gameplay/tools/registerBuiltinComponents'
export { registerBuiltinActors } from './gameplay/tools/registerBuiltinActors'
export { GenericActor } from './gameplay/entity/GenericActor'
export { mergePatch, clonePatch, emptyPatch } from './gameplay/tools/deepMerge'
export type { PropertyPatch } from './gameplay/tools/deepMerge'
export { SaveSystem } from './gameplay/tools/SaveSystem'
export { SAVE_FORMAT_VERSION } from './gameplay/tools/ISaveData'
export type { SaveData, SaveMeta, SaveSlotInfo } from './gameplay/tools/ISaveData'
export { GameUI } from './gameplay/ui/GameUI'
export type { GameUIElement, GameUIOverlay, CreateTextOptions, CreateOverlayOptions } from './gameplay/ui/GameUI'
export { HUD } from './gameplay/ui/HUD'
export { Gizmos, gizmos } from './gameplay/tools/Gizmos'
export type { GizmoColor } from './gameplay/tools/Gizmos'
export { ObjectPool } from './gameplay/tools/ObjectPool'
export type { IPoolable, PoolableActor } from './gameplay/tools/ObjectPool'
export { MeshComponent } from './gameplay/rendering/MeshComponent'
export { DataTable } from './gameplay/tools/DataTable'
export { ConfigRegistry } from './gameplay/tools/ConfigRegistry'
export { InputSys } from './gameplay/input/InputSys'
export { PhySys } from './gameplay/physics/PhySys'
